export enum OrderStatusesEnum {
  WAIT_FOR_PAY = 'WAIT_FOR_PAY',
  WAIT_FOR_INPUT = 'WAIT_FOR_INPUT',
  IN_EXECUTION = 'IN_EXECUTION',
  WAIT_FOR_EXTRA_INPUT = 'WAIT_FOR_EXTRA_INPUT',
  DONE = 'DONE',
  MONEYBACK = 'MONEYBACK',
}
